# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "168d118e58d5e1bd2bd787957e136f2b"
name = "Adray AI Connector"
application_url = "https://adray.ai/connector"
embedded = true
handle = "adnova-ai-connector-1"

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://adray.ai/connector/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  uri = "https://adray.ai/connector/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://adray.ai/connector/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://adray.ai/connector/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_all_orders,read_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://adray.ai/connector/auth/callback",
  "https://adray-app-staging-german.onrender.com/connector/auth/callback"
]
